language: go

go:
  - "1.11.x"

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

before_script:
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck

script:
  - go fmt ./api/...
  - go test -v -race ./api/...                   # Run all the tests with the race detector enabled
  - go vet ./api/...                             # Go static analyzer
  - megacheck ./api/...                          # go vet + linter
  - golint -set_exit_status $(go list ./api/...) # one last linter