language: go

go:
  - "1.11.x"

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck

script:
  - tests -z $(gofmt -s -l $GO_FILES)         # Fail if a .go file hasn't been formatted with gofmt
  - go tests -v -race ./...                   # Run all the tests with the race detector enabled
  - go vet ./...                             # Go static analyzer
  - megacheck ./...                          # go vet + linter
  - golint -set_exit_status $(go list ./...) # one last linter