FROM golang:1.12.1
MAINTAINER Temesxgn Gebrehiwet, temesxgn@gmail.com

WORKDIR /go/src/github.com/temesxgn/redeam
COPY . .

RUN go test -v ./...
RUN go get github.com/pilu/fresh
RUN go get ./...

CMD [ "fresh" ]
