version: '3.3'

services:
  redeam-book-api:
    image: 'redeam/book-api:latest'
    container_name: 'book-api'
    depends_on:
      - 'mongo'
    env_file:
      - './local.env'
    ports:
      - '8080:8080'
    volumes:
      - './:/go/src/github.com/temesxgn/redeam'

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'

  mongo_seed:
    build: './mongo-seed'
